apiVersion: v2
name: helm-test
description: Chart générique pour tests de couverture OpenShift
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: postgresql
    version: "16.7.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "21.2.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
