dependencies:
  - name: postgresql
    version: "10.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "12.6.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
