{{- range $name, $comp := .Values.components }}
{{- if and $comp.pvc $comp.pvc.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-pvc
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ $comp.pvc.storage }}
{{- if $comp.pvc.storageClassName }}
  storageClassName: {{ $comp.pvc.storageClassName }}
{{- else }}
  storageClassName: {{ .Values.defaultStorageClass | default "standard" }}
{{- end }}
{{- end }}
