{{- range $name, $comp := .Values.components }}
{{- if .Values.components.$comp.statefulset.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}-statefulset
spec:
  serviceName: "{{ $name }}-svc"
  replicas: {{ $comp.statefulset.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $comp.statefulset.image | default "busybox" }}
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $comp.pvc.storage | default "1Gi" }}
{{- end }}
{{- end }}
